/**
 * Duas — read from data/duas.json, generated by scripts/build-duas.mjs from
 * Hisn al-Muslim (muslim-data, Apache-2.0) and the Qur'an (AlQuran Cloud).
 * Every dua carries its Arabic text, translations and source reference.
 * Server-only (the JSON is ~800 KB; pages send only what they render).
 */
import raw from "@/data/duas.json";

export type DuaTranslation = {
  language: string;
  label: string;
  text: string;
  dir?: "rtl";
  /** Not a published translation — see scripts/build-duas.mjs. */
  aiAssisted?: boolean;
};

export type Dua = {
  id: string;
  number: number;
  arabic: string;
  transliteration?: string;
  translations: DuaTranslation[];
  reference: string;
  referenceArabic: string;
  source: string;
};

export type DuaChapter = { id: string; title: string; titleArabic: string; duas: Dua[] };

export type DuaCategory = {
  id: string;
  slug: string;
  title: string;
  titleArabic: string;
  source: "quran" | "hisn";
  chapters: DuaChapter[];
  total: number;
};

type RawData = {
  generatedAt: string;
  sources: { name: string; via: string; url: string }[];
  total: number;
  categories: Omit<DuaCategory, "slug" | "total">[];
};

const data = raw as unknown as RawData;

const slugify = (s: string) =>
  s.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const categories: DuaCategory[] = data.categories.map((c) => ({
  ...c,
  slug: c.source === "quran" ? "quran" : slugify(c.title),
  total: c.chapters.reduce((s, ch) => s + ch.duas.length, 0)
}));

export const duaSources = data.sources;
export const totalDuas = data.total;

export function getDuaCategories(): DuaCategory[] {
  return categories;
}

export function getDuaCategory(slug: string): DuaCategory | undefined {
  return categories.find((c) => c.slug === slug);
}

export type DuaSearchResult = {
  dua: Dua;
  categorySlug: string;
  categoryTitle: string;
  chapterId: string;
  chapterTitle: string;
};

const stripMarks = (s: string) =>
  (s || "")
    .toLowerCase()
    .replace(/[ً-ٰٟۖ-ۭـ]/g, "")
    .replace(/[أإآٱ]/g, "ا");

/** Matches chapter titles, translations, transliteration, Arabic (without
 * harakat) and references — e.g. "sleep", "anxiety", "2:201", "Bukhari". */
export function searchDuas(query: string, limit = 30): DuaSearchResult[] {
  const q = stripMarks(query.trim());
  if (!q) return [];
  const results: DuaSearchResult[] = [];
  for (const c of categories) {
    for (const ch of c.chapters) {
      const chapterHit = stripMarks(ch.title).includes(q);
      for (const dua of ch.duas) {
        const hay = [dua.arabic, dua.transliteration, dua.reference, ...dua.translations.map((t) => t.text)]
          .map((s) => stripMarks(s || ""))
          .join(" ");
        if (chapterHit || hay.includes(q)) {
          results.push({ dua, categorySlug: c.slug, categoryTitle: c.title, chapterId: ch.id, chapterTitle: ch.title });
          if (results.length >= limit) return results;
        }
      }
    }
  }
  return results;
}
