/**
 * TafsirProvider
 * ------------------------------------------------------------------
 * Source: the Muslim99 tafsir API (Express + on-disk JSON, see its README)
 * at TAFSIR_API_URL — 122 editions in 33 languages: classical Arabic
 * tafsir, works on grammar (i'rab), qira'at and vocabulary, and
 * translated/modern commentaries (Ibn Kathir, As-Sa'di, Bayan ul Quran,
 * Al-Mukhtasar in 30+ languages, ...).
 *
 * The API only returns slugs, so display metadata (title, author,
 * language, direction, type) comes from data/tafsir-editions.json,
 * generated by scripts/build-tafsir-editions.mjs. Editions the API adds
 * later still appear, with a title derived from the slug, until that
 * script is re-run. Every text shown is attributed to its edition.
 */
import catalogue from "@/data/tafsir-editions.json";

const API = (process.env.TAFSIR_API_URL || "https://gold-owl-974382.hostingersite.com").replace(/\/$/, "");
const DAY = 86400;

export type TafsirEdition = {
  slug: string;
  name: string;
  author: string;
  language: string;
  dir: "rtl" | "ltr";
  type: string;
  surahs: number;
  empty?: boolean;
};

const ALL = catalogue as TafsirEdition[];

/** Every edition with content, in catalogue order. */
export const TAFSIRS: TafsirEdition[] = ALL.filter((e) => !e.empty);

export const DEFAULT_TAFSIR = "ar-tafsir-ibn-kathir";

/** Shown first in pickers — widely read works across the main languages. */
export const FEATURED_TAFSIRS = [
  "ar-tafsir-ibn-kathir",
  "en-tafisr-ibn-kathir",
  "ur-tafseer-ibn-e-kaseer",
  "ar-tafsir-as-saadi",
  "en-tafsir-maarif-ul-quran",
  "tafsir-bayan-ul-quran",
  "ar-tafsir-al-tabari",
  "ar-tafseer-al-qurtubi",
  "ar-tafsir-al-jalalayn",
  "ar-tafsir-muyassar"
];

export function findTafsir(slug: string): TafsirEdition {
  return TAFSIRS.find((t) => t.slug === slug) ?? TAFSIRS.find((t) => t.slug === DEFAULT_TAFSIR) ?? TAFSIRS[0];
}

export function getTafsir(slug: string): TafsirEdition | undefined {
  return TAFSIRS.find((t) => t.slug === slug);
}

/** Languages ordered by number of editions (Arabic, English, Urdu, ...). */
export function tafsirLanguages(): { language: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const t of TAFSIRS) counts.set(t.language, (counts.get(t.language) ?? 0) + 1);
  return Array.from(counts, ([language, count]) => ({ language, count })).sort(
    (a, b) => b.count - a.count || a.language.localeCompare(b.language)
  );
}

async function getJSON<T>(path: string, revalidate = DAY): Promise<T> {
  const res = await fetch(`${API}${path}`, { next: { revalidate } });
  if (!res.ok) throw new Error(`Tafsir API ${res.status}: ${path}`);
  return res.json() as Promise<T>;
}

export type TafsirAyah = { ayah: number; text: string };

export async function getTafsirForSurah(slug: string, surahNumber: number): Promise<TafsirAyah[]> {
  const raw = await getJSON<{ ayahs: unknown }>(`/api/editions/${slug}/surahs/${surahNumber}`);
  // Most editions return { ayahs: [...] }; a few nest it as { ayahs: { ayahs: [...] } }.
  const list = Array.isArray(raw.ayahs) ? raw.ayahs : (raw.ayahs as { ayahs?: unknown[] })?.ayahs ?? [];
  return (list as { ayah: number; text: string }[])
    .filter((v) => typeof v.ayah === "number" && v.text && v.text.trim().length > 0)
    .map((v) => ({ ayah: v.ayah, text: v.text }));
}

export type SurahCoverage = { number: number; withTafsir: number | null };

/** Which surahs an edition covers, with how many ayahs have their own commentary. */
export async function getEditionCoverage(slug: string): Promise<SurahCoverage[]> {
  const data = await getJSON<{ surahs: { number: number; ayahs_with_tafsir: number | null }[] }>(
    `/api/editions/${slug}/surahs`
  );
  return data.surahs.map((s) => ({ number: s.number, withTafsir: s.ayahs_with_tafsir }));
}

export type TafsirSearchResult = { surah: number; ayah: number; snippet: string };

export async function searchTafsir(
  slug: string,
  query: string,
  options?: { surah?: number; limit?: number; offset?: number }
): Promise<{ count: number; results: TafsirSearchResult[] }> {
  const params = new URLSearchParams({ edition: slug, q: query, limit: String(options?.limit ?? 20) });
  if (options?.surah) params.set("surah", String(options.surah));
  if (options?.offset) params.set("offset", String(options.offset));
  const data = await getJSON<{ count: number; results: TafsirSearchResult[] }>(`/api/search?${params}`, 600);
  return { count: data.count, results: data.results.map(({ surah, ayah, snippet }) => ({ surah, ayah, snippet })) };
}

/** A Qur'an translation (alquran.cloud edition) in the tafsir's own
 * language where one exists, so the verse and its commentary match. */
const TRANSLATION_BY_LANGUAGE: Record<string, string> = {
  Urdu: "ur.jalandhry",
  Bengali: "bn.bengali",
  Indonesian: "id.indonesian",
  Turkish: "tr.diyanet",
  Russian: "ru.kuliev",
  French: "fr.hamidullah",
  Spanish: "es.cortes",
  Italian: "it.piccardo",
  Persian: "fa.makarem",
  Hindi: "hi.hindi",
  Chinese: "zh.jian",
  Japanese: "ja.japanese",
  Malayalam: "ml.abdulhameed",
  Tamil: "ta.tamil",
  Thai: "th.thai",
  Uzbek: "uz.sodik",
  Kurdish: "ku.asan",
  Albanian: "sq.nahi",
  Bosnian: "bs.korkut",
  Azerbaijani: "az.mammadaliyev",
  Pashto: "ps.abdulwali",
  Uyghur: "ug.saleh",
  Sinhala: "si.naseemismail"
};

export function translationFor(language: string): string {
  return TRANSLATION_BY_LANGUAGE[language] ?? "en.sahih";
}
