/**
 * TafsirProvider
 * ------------------------------------------------------------------
 * Source: the Muslim99 tafsir API (Express + on-disk JSON, see its README)
 * at TAFSIR_API_URL — 122 editions in 33 languages: classical Arabic
 * tafsir, works on grammar (i'rab), qira'at and vocabulary, and
 * translated/modern commentaries (Ibn Kathir, As-Sa'di, Bayan ul Quran,
 * Al-Mukhtasar in 30+ languages, ...).
 *
 * The API only returns slugs, so display metadata (title, author,
 * language, direction, type) comes from data/tafsir-editions.json,
 * generated by scripts/build-tafsir-editions.mjs. Editions the API adds
 * later still appear, with a title derived from the slug, until that
 * script is re-run. Every text shown is attributed to its edition.
 *
 * A further set of Urdu tafsirs (Tafheem ul Quran, Ahsan ul Bayan,
 * Maarif-ul-Quran, ...) is served from this site's own files
 * (data/quran_db, from quran.db — see scripts/build-quran-db.mjs); those
 * editions have `local: true`. The fetchers are in lib/tafsirData.ts
 * (server-only); this file is also used by client components.
 */
import catalogue from "@/data/tafsir-editions.json";
import localCatalogue from "@/data/quran_db/meta.json";

export type TafsirEdition = {
  slug: string;
  name: string;
  author: string;
  language: string;
  dir: "rtl" | "ltr";
  type: string;
  surahs: number;
  empty?: boolean;
  /** Served from data/quran_db rather than the tafsir API. */
  local?: boolean;
};

const ALL = catalogue as TafsirEdition[];

const LOCAL: TafsirEdition[] = localCatalogue.tafsirs.map(({ coverage: _coverage, ...e }) => ({
  ...e,
  dir: e.dir as "rtl" | "ltr",
  local: true
}));

/** Every edition with content, in catalogue order. */
export const TAFSIRS: TafsirEdition[] = [...ALL.filter((e) => !e.empty), ...LOCAL];

export const DEFAULT_TAFSIR = "ar-tafsir-ibn-kathir";

/** Shown first in pickers — widely read works across the main languages. */
export const FEATURED_TAFSIRS = [
  "ar-tafsir-ibn-kathir",
  "en-tafisr-ibn-kathir",
  "ur-tafseer-ibn-e-kaseer",
  "ur-tafheem-ul-quran",
  "ur-ahsan-ul-bayan",
  "ar-tafsir-as-saadi",
  "en-tafsir-maarif-ul-quran",
  "tafsir-bayan-ul-quran",
  "ar-tafsir-al-tabari",
  "ar-tafseer-al-qurtubi",
  "ar-tafsir-al-jalalayn",
  "ar-tafsir-muyassar"
];

export function findTafsir(slug: string): TafsirEdition {
  return TAFSIRS.find((t) => t.slug === slug) ?? TAFSIRS.find((t) => t.slug === DEFAULT_TAFSIR) ?? TAFSIRS[0];
}

export function getTafsir(slug: string): TafsirEdition | undefined {
  return TAFSIRS.find((t) => t.slug === slug);
}

/** Languages ordered by number of editions (Arabic, English, Urdu, ...). */
export function tafsirLanguages(): { language: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const t of TAFSIRS) counts.set(t.language, (counts.get(t.language) ?? 0) + 1);
  return Array.from(counts, ([language, count]) => ({ language, count })).sort(
    (a, b) => b.count - a.count || a.language.localeCompare(b.language)
  );
}

/** A Qur'an translation (alquran.cloud edition) in the tafsir's own
 * language where one exists, so the verse and its commentary match. */
const TRANSLATION_BY_LANGUAGE: Record<string, string> = {
  Urdu: "ur.jalandhry",
  Bengali: "bn.bengali",
  Indonesian: "id.indonesian",
  Turkish: "tr.diyanet",
  Russian: "ru.kuliev",
  French: "fr.hamidullah",
  Spanish: "es.cortes",
  Italian: "it.piccardo",
  Persian: "fa.makarem",
  Hindi: "hi.hindi",
  Chinese: "zh.jian",
  Japanese: "ja.japanese",
  Malayalam: "ml.abdulhameed",
  Tamil: "ta.tamil",
  Thai: "th.thai",
  Uzbek: "uz.sodik",
  Kurdish: "ku.asan",
  Albanian: "sq.nahi",
  Bosnian: "bs.korkut",
  Azerbaijani: "az.mammadaliyev",
  Pashto: "ps.abdulwali",
  Uyghur: "ug.saleh",
  Sinhala: "si.naseemismail"
};

export function translationFor(language: string): string {
  return TRANSLATION_BY_LANGUAGE[language] ?? "en.sahih";
}
