import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/shared/Footer';
import Header from '@/components/shared/Header';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: '200',
});

const poppinsMedium = Poppins({
  variable: '--font-poppins-medium',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppinsMedium.variable} antialiased`}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
